export const feedbackList = [
  {
    id: 1,
    name: 'Ольга Іваненко',
    rating: 5,
    time: '2 тижні тому',
    text: 'Замовляла корекцію весільної сукні, і це був просто ідеальний сервіс! Олена врахувала всі мої побажання, і сукня сіла ідеально. Дуже дякую за вашу роботу!',
    photo: '/img/f-1.webp',
  },
  {
    id: 2,
    name: 'Анастасия Морозова',
    rating: 4,
    time: '1 місяць тому',
    text: 'Брала напрокат вечернее платье для свадьбы подруги. Платье было потрясающее! Елена помогла подобрать подходящий вариант. Спасибо за внимание и заботу!',
    photo: '/img/f-2.webp',
  },
  {
    id: 3,
    name: 'Катерина Петрова',
    rating: 5,
    time: '3 місяці тому',
    text: 'Робила корекцію вечірнього плаття перед важливою подією. Завдяки Олені плаття виглядає просто чудово. Дуже задоволена результатом!',
    photo: '/img/f-3.webp',
  },
  {
    id: 4,
    name: 'Марія Лебедєва',
    rating: 5,
    time: '1 тиждень тому',
    text: 'Орендувала плаття для корпоративу. Вибір неймовірний! Дякую за терпіння та поради. Сукня зробила мій вечір незабутнім.',
    photo: '/img/f-4.webp',
  },
  {
    id: 5,
    name: 'Ірина Гончарук',
    rating: 5,
    time: '2 місяці тому',
    text: 'Коригувала повсякденну сукню після схуднення. Робота зроблена якісно. Олена дуже привітна і професійна.',
    photo: '/img/f-5.webp',
  },
  {
    id: 6,
    name: 'Анна Степанова',
    rating: 5,
    time: '1 день тому',
    text: 'Замовляла шлейф для весільної сукні. Хочу подякувати Олені за її професіоналізм і розуміння всіх моїх побажань. Сукня вийшла просто казкова!',
    photo: '/img/f-6.webp',
  },
  {
    id: 7,
    name: 'Юлія Савченко',
    rating: 5,
    time: '1 місяць тому',
    text: 'Брала напрокат вечернее платье для бала. Очень понравился сервис! Елена лично помогла выбрать платье, которое идеально подошло. Спасибо за индивидуальный подход!',
    photo: '/img/f-7.webp',
  },
  {
    id: 8,
    name: 'Наталя Кириченко',
    rating: 5,
    time: '5 днів тому',
    text: 'Дуже задоволена орендою плаття! Замовляла сукню для фотосесії. Все було вчасно, плаття як нове. Дякую за професійність.',
    photo: '/img/f-8.webp',
  },
  {
    id: 9,
    name: 'Тетяна Литвин',
    rating: 4,
    time: '2 місяці тому',
    text: 'Коригувала вечірнє плаття, яке зіпсували в іншому ательє. Тут все виправили! Дякую Елені за терпіння і якісний сервіс.',
    photo: '/img/f-9.webp',
  },
  {
    id: 10,
    name: 'Вікторія Романенко',
    rating: 5,
    time: '3 тижні тому',
    text: 'Взяла напрокат повсякденну сукню для ділової зустрічі. Все було чудово! Окремо дякую за теплий прийом і допомогу з вибором.',
    photo: '/img/f-10.webp',
  },
  {
    id: 11,
    name: 'Anna Nováková',
    rating: 5,
    time: '1 týden zpět',
    text: 'Objednala jsem si večerní šaty na ples a všechno bylo perfektní. Šaty mi padly jako ulité a děkuji za skvělý servis!',
    photo: '/img/f-11.webp',
  },
  {
    id: 12,
    name: 'Jana Dvořáková',
    rating: 4,
    time: '2 týdny zpět',
    text: 'Pronajala jsem si svatební šaty a musím říct, že vše proběhlo hladce. Šaty byly nádherné, díky moc!',
    photo: '/img/f-12.webp',
  },
  {
    id: 13,
    name: 'Petra Svobodová',
    rating: 5,
    time: '3 týdny zpět',
    text: 'Nechala jsem si upravit své večerní šaty a jsem nadšená. Děkuji za profesionální přístup!',
    photo: '/img/f-13.webp',
  },
  {
    id: 14,
    name: 'Emily Johnson',
    rating: 5,
    time: '1 month ago',
    text: 'I rented a dress for my best friend’s wedding, and it was stunning! Thank you for the amazing service and attention to detail!',
    photo: '/img/f-14.webp',
  },
  {
    id: 15,
    name: 'Sophia Brown',
    rating: 4,
    time: '2 weeks ago',
    text: 'Got my evening dress adjusted here, and it was done beautifully. Thank you for making my day so special!',
    photo: '/img/f-15.webp',
  },
];
